# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Resources
    url: /#papers
    weight: 11
  - name: Events
    url: /#talks
    weight: 12
  - name: News
    url: /#news
    weight: 13
  - name: Team
    url: experience/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Privacy Policy
    url: teaching/
    weight: 40
